[build]
  publish = "."

[functions]
  directory = "وظائفnetlify"

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/store"
  status = 200
  force = true

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public,max-age=0,must-revalidate"
